package com.afya.portal.service;

/**
 * Created by User on 10/22/2015.
 */
public enum TemplateNames {
    PATIENT_CONFIRMATION,
    PATIENT_REGISTRATION,
    PROVIDER_CONFIRMATION,
    PAYER_CONFIRMATION,
    PROVIDER_REGISTRATION,
    PROVIDER_SUBSCRIPTION_TRIAL,
    PROVIDER_SUBSCRIPTION,
    RESET_PASSWORD,
    PACKAGE_QUOTATION,
    SUBSCRIPTION,

    WELCOME_ATTACHMENT_PATIENT,
    WELCOME_ATTACHMENT_PROVIDER_TRIAL,
    WELCOME_ATTACHMENT_PROVIDER_SUBSCRIPTION,

    PATIENT_REGISTRATION_SMS,
    PROVIDER_SUBSCRIPTION_TRIAL_SMS,
    PROVIDER_SUBSCRIPTION_SMS,

    AUTO_REGISTERED_PATIENT_PASSWORD
}
